### ISSUE TITLE
условие

### ISSUE THREAD

**Issue by pecourses** [schaslivchik/js_homework_1#1]
https://github.com/schaslivchik/js_homework_1/blob/4645a3e766dd5fa5f1663beb481288823f801fa7/js/index.js#L83
- немного не дочитали условие про 500 грн

**Comment by schaslivchik** [comment]
[const amount = Number (prompt('Введите суму '));
if(amount >= 500 && amount <= 800) {
   alert(amount - (amount * 3 / 100) + ' скидка 3%');
 } else if(amount > 800){
  alert(amount - (amount * 5 / 100) + ' скидка 5%');
 } else { 
     alert('скидки нету');
 }](https://github.com/schaslivchik/js_homework_1/blob/83a10d40c9743b099579dd92b580eecb00eb7c0e/js/index.js#L78)

**Comment by schaslivchik** [comment]
**обновил**
const amount = Number (prompt('Введите суму '));
if(amount >= 500 && amount <= 800) {
alert(amount - (amount * 3 / 100) + ' скидка 3%');
} else if(amount > 800){
alert(amount - (amount * 5 / 100) + ' скидка 5%');
} else {
alert('скидки нету');
}

**Comment by pecourses** [comment]
При 500 скидки по условию нет
